### ISSUE TITLE
Unable to level up in psi

### ISSUE THREAD

**Issue by Phoenix116** [FTBTeam/FTB-Presents-Stoneblock-2#129]
* **Modpack Version**: 1.1.1

* **Issue**: When I use the debug spell to complete the tutorial and reach level 2 to continue the mod, it just doesn't level up and stucks in level 1 forever (I have tried even copying the spell from a guide)

* **Is it Repeatable?**: Yes, I have tried in singleplayer and in multiplayer, both times the bug ocurred
![image](https://user-images.githubusercontent.com/46644927/51083967-c4d2ff80-1722-11e9-93a9-c1d23ab95dfb.png)
![image](https://user-images.githubusercontent.com/46644927/51083972-df0cdd80-1722-11e9-851b-9a86399b4164.png)
![image](https://user-images.githubusercontent.com/46644927/51083975-f0ee8080-1722-11e9-8df4-eb43f2a8a956.png)

**Comment by Sunekaer** [comment]
Could you try and update PSI and tell me if it still happens?

**Comment by Boomflex** [comment]
https://github.com/Vazkii/Psi/issues/467

Looks like it has been fixed in a newer update?

**Comment by Phoenix116** [comment]
I have tried using the lastest version (1.1-69) and the bug is still happening
Fortunately with the new command /psi-learn you are able to learn the 2º mission and keep making progress through the mod normaly, it seems to only be bugged the first mission

**Comment by Boomflex** [comment]
Can you report this to Vazkii on his tracker then please :)

**Comment by yrsegal** [comment]
Try learning the spell group again. It might have been unselected, due to the way the update worked.
