### ISSUE TITLE
Ender Chicken crashing

### ISSUE THREAD

**Issue by Slyklaw** [FTBTeam/FTB-Presents-Stoneblock-2#13]
Ender Chicken was crashing people in 1.0.0. Downloading 1.0.1 to test if it still exists. Will update/close issue shortly.

**Comment by Sunekaer** [comment]
log?

**Comment by Slyklaw** [comment]
Here's a crash report from 1.0.0.
[crash-2019-01-04_10.27.12-server.txt](https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/files/2727390/crash-2019-01-04_10.27.12-server.txt)

**Comment by Sunekaer** [comment]
Is it still happing in 1.0.1?

**Comment by Slyklaw** [comment]
Not yet tested, too many active players. Soon.

**Comment by Sunekaer** [comment]
Okay i need that answer but going to the dev with the crash, as this should be fixed in 1.0.1

**Comment by Slyklaw** [comment]
Updated to 1.0.1 and no crash yet, so this is probably fixed. I'll close shortly after some additional testing.

**Comment by NicolBolas71** [comment]
Can confirm it still happens in version 1.0.1
[crash-2019-01-05_01.59.46-server.txt](https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/files/2729065/crash-2019-01-05_01.59.46-server.txt)

**Comment by NicolBolas71** [comment]
ok im back, after updating the server to the correct version and a few minutes after the ender chicken was killedgot the exact same error

newest crash report
[crash-2019-01-05_02.50.03-server.txt](https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/files/2729089/crash-2019-01-05_02.50.03-server.txt)

**Comment by Slyklaw** [comment]
Yup, still happening. New 1.0.1 crash report attached.

[crash-2019-01-05_04.40.10-server.txt](https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/files/2729174/crash-2019-01-05_04.40.10-server.txt)

**Comment by Sunekaer** [comment]
Please upload logs via https://paste.feed-the-beast.com

**Comment by NicolBolas71** [comment]
done

https://paste.feed-the-beast.com/view/94fe85ce

**Comment by Slyklaw** [comment]
https://paste.feed-the-beast.com/view/13401fa9
https://paste.feed-the-beast.com/view/3f42ea02

**Comment by MacAndSwiss** [comment]
https://paste.feed-the-beast.com/view/4995457e

Here's my crash log. Seems to be an issue with the mod itself.

**Comment by Sunekaer** [comment]
When in the fight does this crash happen?

**Comment by Sunekaer** [comment]
For the java.util.ConcurrentModificationException crash are people spam dropping the item or do they just drop one item and it crashed?

**Comment by Sunekaer** [comment]
@MacAndSwiss yours is another crash

**Comment by NicolBolas71** [comment]
our crash happened 3 or 4 minutes after he killed the ender chicken after updating to 1.0.1

**Comment by Sunekaer** [comment]
@NicolBolas71 
We are not able to recreate this problem on our test servers, so could you try and update the server to this version, it would also require the people join to update the mod, and test with that
https://s1.sunekaer.com/SB2/MightyEnderChicken-1.12.2-7.0.0-beta23.jar

**Comment by ChosenArchitect** [comment]
@Sunekaer we will have to wait till the pack is updated on curse because It would be too confusing for all people as we have on the server...

**Comment by NicolBolas71** [comment]
ok we just killed it again on our server, and it was when the guy used the home command to teleport home after killing the chicken it crashed with the error log i have already posted

**Comment by Sunekaer** [comment]
Still cant recreate the issue

**Comment by NicolBolas71** [comment]
ok we have done what you asked, updated to the file you gave me to use , have a possible idea of the culprit, after installing the file we fought the chicken 2 times, the first time was with a skullfire sword, and it didnt crash right away, then another player was fighting one and died, the server crashed, he went back in and finished the fight using shurikens, so im wondering if its a tinkers conflict. not sure however. here is the latest crash report

https://paste.feed-the-beast.com/view/a8f73a93

**Comment by Sunekaer** [comment]
Should be fixed in 1.1.0
