### ISSUE TITLE
Tesla Libary Crashes on World Load

### ISSUE THREAD

**Issue by byBackfish** [FTBTeam/FTB-Presents-Stoneblock-2#549]
ding mods like optifine to the modpack! So please remove all added content, 
re-test bug/issue and resubmit!

* **Modpack Version**: 1.14.0

* **Issue**: On Worldload a Crash with Tesla Libary apperas. Cant fix it

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: Every WorldLoad

* **Mod/s Affected**: Tesla Libary

* **Known Fix**: I dot know any

**Comment by Sunekaer** [comment]
log?

**Comment by byBackfish** [comment]
Sry I forgot it. But thanks I fixed it already :)

**Comment by polyamide** [comment]
I have the same crashes, here's the log:

https://paste.dimdev.org/unakusekow.mccrash

**Comment by polyamide** [comment]
Additional info:

- Restart minecraft didn't help
- Update Stoneblock to 1.15.0 still won't work
- It first happen when I trying to use Potion brewer (industrial foregoing)

Another crash log (from stoneblock 1.15): https://paste.dimdev.org/ikudepeduc.mccrash
